- name: Install ZSH, Oh-my-zsh and Powerlevel10k + fonts
  # Change hosts depending on inventory file.
  hosts: localhost
  tasks:
    - name: Get current user
      command: whoami
      register: current_user

    - name: Get zsh_custom directory
      command: echo "/home/{{ current_user.stdout }}/.oh-my-zsh/custom"
      register: zsh_custom

    - name: Install ZSH
      apt:
        name: zsh
        state: present
        update_cache: true
      become: True

    - name: Print ZSH version
      command: zsh --version

    - name: Set default shell to zsh
      shell: "chsh {{ current_user.stdout }} -s /bin/zsh"
      become: True

    - name: Install Oh-my-zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

    - name: Downloading plugins for Oh-My-ZSH
      command: git clone https://github.com/zsh-users/{{ item }}.git {{ zsh_custom.stdout }}/plugins/{{ item }}
      loop:
        - zsh-syntax-highlighting
        - zsh-autosuggestions

    - name: Install powerline fonts
      apt:
        name: fonts-powerline
        update_cache: true
      become: yes

    - name: Install Powerlevel 10k
      command: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git {{ zsh_custom.stdout }}/themes/powerlevel10k

    - name: Apply predefined p10k.zsh
      copy:
        src: dotfiles/.p10k.zsh
        dest: ~/.p10k.zsh

    - name: Apply predefined ~/.zshrc
      copy:
        src: dotfiles/.zshrc
        dest: ~/.zshrc
