- name: Install ZSH, Oh-my-zsh and Powerlevel10k + fonts
  hosts: localhost
  vars:
    current_user: "{{ ansible_user_id }}"
    zsh_custom: "/home/{{ current_user }}/.oh-my-zsh/custom"
  tasks:
    - name: "DEBUG: Remove any previous plugins"
      shell: rm -rf "{{ item }}"
      loop:
        - "{{ zsh_custom }}/plugins/zsh-syntax-highlighting"
        - "{{ zsh_custom }}/plugins/zsh-autosuggestions"
        - /home/{{ current_user }}/.oh-my-zsh
      become: true

    - name: Install Git
      apt:
        name: git
        state: present
        update_cache: true
      become: true

    - name: Install curl
      apt:
        name: curl
        state: present
        update_cache: true
      become: true

    - name: Install ZSH
      apt:
        name: zsh
        state: present
        update_cache: true
      become: true

    - name: Print ZSH version
      shell: zsh --version

    - name: Set default shell
      become: true
      user:
        name: "{{ current_user }}"
        shell: /bin/zsh

    - name: Install Oh-my-zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

    - name: Downloading plugins for Oh-My-ZSH
      shell: "git clone https://github.com/zsh-users/{{ item }}.git {{ zsh_custom }}/plugins/{{ item }}"
      loop:
        - zsh-syntax-highlighting
        - zsh-autosuggestions
      become: true

    - name: Install powerline fonts
      apt:
        name: fonts-powerline
        update_cache: true
      become: true

    - name: Install Powerlevel 10k
      shell: "git clone --depth=1 https://github.com/romkatv/powerlevel10k.git {{ zsh_custom }}/themes/powerlevel10k"

    - name: Apply predefined p10k.zsh
      copy:
        src: zsh_templates/p10k.template
        dest: ~/.p10k.zsh

    - name: Apply predefined ~/.zshrc
      copy:
        src: zsh_templates/zshrc.template
        dest: ~/.zshrc

    - name: Logout of terminal
      shell: exit

    - name: Installation finished.
      debug:
        msg: Restart your terminal.
