- name: Install ZSH, Oh-my-zsh and Powerlevel10k + fonts
  # Change hosts depending on inventory file.
  hosts: localhost
  tasks:
    - name: Get current user
      ansible.builtin.command: whoami
      register: current_user
      changed_when: current_user.stdout | length > 0

    - name: Get zsh_custom directory
      ansible.builtin.command: echo "/home/{{ current_user.stdout }}/.oh-my-zsh/custom"
      register: zsh_custom
      changed_when: "{{current_user.stdout}} in zsh_custom.stdout"

    - name: Install ZSH
      ansible.builtin.apt:
        name: zsh
        state: present
        update_cache: true
      become: true
      changed_when: false

    - name: Print ZSH version
      ansible.builtin.command: zsh --version
      changed_when: false

    - name: Set default shell to zsh
      ansible.builtin.command: "chsh {{ current_user.stdout }} -s /bin/zsh"
      become: true
      changed_when: false

    - name: Install cURL
      ansible.builtin.apt:
        name: curl
        update_cache: true
      become: true

    - name: Install Oh-my-zsh
      ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      changed_when: false

    - name: Downloading plugins for Oh-My-ZSH
      ansible.builtin.command: git clone https://github.com/zsh-users/{{ item }}.git {{ zsh_custom.stdout }}/plugins/{{ item }}
      loop:
        - zsh-syntax-highlighting
        - zsh-autosuggestions
      changed_when: false

    - name: Install powerline fonts
      ansible.builtin.apt:
        name: fonts-powerline
        update_cache: true
      become: true
      changed_when: false

    - name: Install Powerlevel 10k
      ansible.builtin.command: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git {{ zsh_custom.stdout }}/themes/powerlevel10k
      changed_when: false

    - name: Apply predefined p10k.zsh
      ansible.builtin.copy:
        src: dotfiles/.p10k.zsh
        dest: ~/.p10k.zsh
      changed_when: false

    - name: Apply predefined ~/.zshrc
      ansible.builtin.copy:
        src: dotfiles/.zshrc
        dest: ~/.zshrc
      changed_when: false
