version: "2"

networks:
  home1macnetwork:
    name: home1macnetwork
    driver: macvlan
    driver_opts:
      parent: ens18
    ipam:
      config:
        - subnet: 192.168.0.0/24

services:
  adguard-home:
    image: adguard/adguardhome
    container_name: adguard-home
    ports:
      - 5553:53/tcp
      - 5553:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3001:3000/tcp
      - 81:80/tcp
      - 4443:443/tcp
    volumes:
      - /data/adguard/workdir:/opt/adguardhome/work
      - /data/adguard/confdir:/opt/adguardhome/conf
    restart: unless-stopped

    networks:
      home1macnetwork:
        ipv4_address: 192.168.0.21 # UNUSED IP on network
