version: "3"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - NET_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL=${DDNS_SERVER_URL}
      - SERVERPORT=51820
      - PEERS=1
      - PEERDNS=auto
      - ALLOWEDIPS=0.0.0.0/0
      - LOG_CONFS=true
    volumes:
      - /data/wireguard/config:/config
      - /data/wireguard/lib/modules:/lib/modules
    sysctls:
      - "net.ipv4.conf.all.src_valid_mark=1"
    restart: unless-stopped
