- hosts: localhost
  become: true
  tasks:
    - name: Remove previous versions of Docker
      apt:
        state: absent
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc

    - name: Set up Docker repository
      block:
        - name: Install prerequisite packages
          apt:
            name:
              - ca-certificates
              - curl
              - gnupg
              - lsb-release
            update_cache: true

        - name: Add Docker GPG key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg

        - name: Get Linux Linux Release
          shell: lsb_release -cs
          register: lsb_release

        - name: Add Docker repository
          apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable

    - name: Install Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        update_cache: true

    - name: Add user to docker group
      shell: usermod -aG docker $USER

    - name: Verify Docker Engine is installed
      shell: docker --version

    - name: Verify Docker Compose is installed
      shell: docker compose version

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Verify Docker Hello World can be started.
      shell: docker run hello-world
