- name: Install Docker
  hosts: localhost
  become: true
  tasks:
    - name: Remove previous versions of Docker
      ansible.builtin.apt:
        state: absent
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc

    - name: Set up Docker repository
      block:
        - name: Install prerequisite packages
          ansible.builtin.apt:
            name:
              - ca-certificates
              - curl
              - gnupg
              - lsb-release
            update_cache: true

        - name: Add Docker GPG key
          ansible.builtin.apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg

        - name: Get Linux Release
          ansible.builtin.command: lsb_release -cs
          register: lsb_release
          changed_when: false

        - name: Add Docker repository
          ansible.builtin.apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable

    - name: Install Docker Engine
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        update_cache: true

    - name: Ensure docker group
      ansible.builtin.group:
        name: docker
        state: present
      changed_when: false

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
      changed_when: false

    - name: Add user to docker group
      ansible.builtin.shell: usermod -aG docker $USER
      changed_when: false

    - name: Verify Docker Engine is installed
      ansible.builtin.command: docker --version
      changed_when: false

    - name: Verify Docker Compose is installed
      ansible.builtin.command: docker compose version
      changed_when: false

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started

    - name: Verify Docker Hello World can be started.
      ansible.builtin.command: docker run hello-world
      changed_when: false
